# Generated by Django 5.0.1 on 2024-01-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
